name: BuildNuGetAndPublish

on:
  create:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_CONFIG: Release
      SOLUTION: PingenApiNet.sln

    steps:
      - uses: actions/checkout@v5.0.0

      - name: Get Build Version
        run: |
          Import-Module .\build\GetBuildVersion.psm1
          Write-Host $Env:GITHUB_REF
          $version = GetBuildVersion -VersionString $Env:GITHUB_REF
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore $SOLUTION

      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore

      - name: Pack
        run: dotnet pack $SOLUTION --configuration $BUILD_CONFIG -p:PackageVersion=$BUILD_VERSION --no-build

      - name: Publish to NuGet
        run: dotnet nuget push "**/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key "${{ secrets.NUGET_API_KEY }}" --skip-duplicate
